require("__khaosbioprocessinggroup__.prototypes.compat.aquilo-seabloom-algaculture-final-fixes")
require("__khaosbioprocessinggroup__.prototypes.compat.astroponics-final-fixes")
require("__khaosbioprocessinggroup__.prototypes.compat.cerys-lunaponics-final-fixes")
require("__khaosbioprocessinggroup__.prototypes.compat.fulgora-coralmium-agriculture-final-fixes")
require("__khaosbioprocessinggroup__.prototypes.compat.vulcanus-sulfuric-bacteria-final-fixes")
